/* NOTIFICATION */
export const DISPLAY_ERROR_PAGE = "DISPLAY_ERROR_PAGE";
export const WRITE_ERROR_MESSAGE = "WRITE_ERROR_MESSAGE";
export const CREATE_NEW_NOTIFICATION = "CREATE_NEW_NOTIFICATION";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_ERROR_MESSAGES = "CLEAR_ERROR_MESSAGES";

/* API */
// export const LOCATION_DATA = 'LOCATION_DATA';

// export const FETCH_LOCATION_DATA = 'FETCH_LOCATION_DATA';

// export const CREATE_NEW_LOCATION = 'CREATE_NEW_LOCATION';

/* settings */
export const ENTER_LOGIN_VIEW = "ENTER_LOGIN_VIEW";
export const LEAVE_LOGIN_VIEW = "LEAVE_LOGIN_VIEW";

export const ENTER_HOME_VIEW = "ENTER_HOME_VIEW";
export const LEAVE_HOME_VIEW = "LEAVE_HOME_VIEW";
export const ENTER_SIMPLE_TABLES_VIEW = "ENTER_SIMPLE_TABLES_VIEW";
export const LEAVE_SIMPLE_TABLES_VIEW = "LEAVE_SIMPLE_TABLES_VIEW";
export const ENTER_BASIC_ELEMENTS_VIEW = "ENTER_BASIC_ELEMENTS_VIEW";
export const LEAVE_BASIC_ELEMENTS_VIEW = "LEAVE_BASIC_ELEMENTS_VIEW";
export const ENTER_GENERAL_VIEW = "ENTER_GENERAL_VIEW";
export const LEAVE_GENERAL_VIEW = "LEAVE_GENERAL_VIEW";
export const ENTER_PAGE_NOT_FOUND_VIEW = "ENTER_PAGE_NOT_FOUND_VIEW";
export const LEAVE_PAGE_NOT_FOUND_VIEW = "LEAVE_PAGE_NOT_FOUND_VIEW";
export const ENTER_STATS_CARD_VIEW = "ENTER_STATS_CARD_VIEW";
export const LEAVE_STATS_CARD_VIEW = "LEAVE_STATS_CARD_VIEW";
export const ENTER_EARNING_GRAPH_VIEW = "ENTER_EARNING_GRAPH_VIEW";
export const LEAVE_EARNING_GRAPH_VIEW = "LEAVE_EARNING_GRAPH_VIEW";
export const ENTER_NOTIFICATIONS_VIEW = "ENTER_NOTIFICATIONS_VIEW";
export const LEAVE_NOTIFICATIONS_VIEW = "LEAVE_NOTIFICATIONS_VIEW";
export const ENTER_WORK_PROGRESS_VIEW = "ENTER_WORK_PROGRESS_VIEW";
export const LEAVE_WORK_PROGRESS_VIEW = "LEAVE_WORK_PROGRESS_VIEW";
export const ENTER_TWITTER_FEED_VIEW = "ENTER_TWITTER_FEED_VIEW";
export const LEAVE_TWITTER_FEED_VIEW = "LEAVE_TWITTER_FEED_VIEW";
export const ENTER_TEAM_MATES_VIEW = "ENTER_TEAM_MATES_VIEW";
export const LEAVE_TEAM_MATES_VIEW = "LEAVE_TEAM_MATES_VIEW";
export const ENTER_TODO_LIST_VIEW = "ENTER_TODO_LIST_VIEW";
export const LEAVE_TODO_LIST_VIEW = "LEAVE_TODO_LIST_VIEW";
export const ENTER_BREADCRUMB_VIEW = "ENTER_BREADCRUMB_VIEW";
export const LEAVE_BREADCRUMB_VIEW = "LEAVE_BREADCRUMB_VIEW";
export const ENTER_STAT_VIEW = "ENTER_STAT_VIEW";
export const LEAVE_STAT_VIEW = "LEAVE_STAT_VIEW";
export const ENTER_BASIC_PROGRESS_BAR_VIEW = "ENTER_BASIC_PROGRESS_BAR_VIEW";
export const LEAVE_BASIC_PROGRESS_BAR_VIEW = "LEAVE_BASIC_PROGRESS_BAR_VIEW";
export const ENTER_TAB_PANEL_VIEW = "ENTER_TAB_PANEL_VIEW";
export const LEAVE_TAB_PANEL_VIEW = "LEAVE_TAB_PANEL_VIEW";
export const ENTER_STRIPED_PROGRESS_BAR_VIEW =
  "ENTER_STRIPED_PROGRESS_BAR_VIEW";
export const LEAVE_STRIPED_PROGRESS_BAR_VIEW =
  "LEAVE_STRIPED_PROGRESS_BAR_VIEW";
export const ENTER_ALERT_VIEW = "ENTER_ALERT_VIEW";
export const LEAVE_ALERT_VIEW = "LEAVE_ALERT_VIEW";
export const ENTER_PAGINATION_VIEW = "ENTER_PAGINATION_VIEW";
export const LEAVE_PAGINATION_VIEW = "LEAVE_PAGINATION_VIEW";
export const ENTER_PROTECTED_VIEW = "ENTER_PROTECTED_VIEW";
export const LEAVE_PROTECTED_VIEW = "LEAVE_PROTECTED_VIEW";
export const SIDEMU_IS_COLLAPSED_KEY = true;
export const SIDEMU_IS_NOT_COLLAPSED_VALUE = false;
export const READ_LOCALSTORAGE = false;
export const WRITE_LOCALSTORAGE = true;
export const OPEN_SIDE_MENU = "OPEN_SIDE_MENU";
export const CLOSE_SIDE_MENU = "CLOSE_SIDE_MENU";
export const GET_SIDE_MENU_TOGGLE_STATE_FROM_LOCALSTORAGE =
  "GET_SIDE_MENU_TOGGLE_STATE_FROM_LOCALSTORAGE";
export const ON_LOADER_SHOW = "ON_LOADER_SHOW";
export const ON_LOADER_HIDE = "ON_LOADER_HIDE";
export const ON_ICE_LOADER_SHOW = "ON_ICE_LOADER_SHOW";
export const ON_ICE_LOADER_HIDE = "ON_ICE_LOADER_HIDE";

/* Data Actions */
export const FETCH_FEATURE_IMPORTANCE = "FETCH_FEATURE_IMPORTANCE";
export const FEATURE_IMPORTANCE_DATA = "FEATURE_IMPORTANCE_DATA";
export const FETCH_FEATURE_ICE_COORDS = "FETCH_FEATURE_ICE_COORDS";
export const FEATURE_ICE_COORDS = "FEATURE_ICE_COORDS";
